---
title: "Untitled"
author: "Victor Harbo Johnston"
date: "9/17/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
res = GET("https://api.trove.nla.gov.au/v2/result?key=p75vgrks9qi358s0&q=danish+AND+immigrant&zone=newspaper&encoding=json&n=100&bulkHarvest=true&s=*")
```

```{r}
data <- fromJSON(rawToChar(res$content))
df <- data.frame(data$response$zone$records$article)

end <- data$response$zone$records$"nextStart"
end
```

```{r}
call <- paste0("https://api.trove.nla.gov.au/v2/result?key=p75vgrks9qi358s0&q=danish+AND+immigrant&zone=newspaper&encoding=json&n=100&bulkHarvest=true&s=",end)
call

res2 = GET(call)
data2 <- fromJSON(rawToChar(res2$content))
df <- bind_rows(df, data.frame(data2$response$zone$records$article))
#df2 <- data.frame(data2$response$zone$records$article)
```
```{r}
count(df, id)

end2 <- data2$response$zone$records$"nextStart"
end2
```


```{r}
call <- c()
response <- c()
data <- tibble(df$response$zone$records$article)
```

```{r}
for (i in df$response$zone$records$"nextStart"){
  call <- paste0("https://api.trove.nla.gov.au/v2/result?key=p75vgrks9qi358s0&q=danish+AND+immigrant&zone=newspaper&encoding=json&n=100&bulkHarvest=true&s=", i )
  response <- fromJSON(call)
  data <- bind_rows(data, response$response$zone$records$article)
}
```

